export default {
  entries: [
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (10).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (11).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (12).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (13).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (14).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (15).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (16).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (18).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (19).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (1).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (20).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (21).jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (23).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (24).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (25).jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (26).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (2).jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (3).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (4).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (6).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (7).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (8).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (9).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1.JPG.avif') },
  ],
  name: '16.04. Düsseldorf',
}
