import EntryBuilder from '~/models/builder/gallery/EntryBuilder'
import GalleryBuilder from '~/models/builder/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.Vereinsfahrt)
    .dateFrom(new Date('2011-03-27'))
    .dateTo(new Date('2011-08-06'))
    .location('Düren-Merken, Düsseldorf & Lülsdorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/01_01_Rueckblick.gif').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/03_27_Dueren-Merken/DSCF1156.JPG').previewUrl().build(), '27.03. Düren-Merken')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (10).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (11).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (12).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (13).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (14).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (15).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (16).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (18).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (19).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (1).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (20).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (21).jpg').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (23).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (24).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (25).jpg').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (26).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (2).jpg').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (3).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (4).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (6).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (7).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (8).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1 (9).JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/04_16_Duesseldorf/DSCF 1.JPG').previewUrl().build(), '16.04. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/05_08_Luelsdorf/RTF Luelsdorf 003.jpg').previewUrl().build(), '08.05. Lülsdorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3373.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3376.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3390.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3391.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3397.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3399.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3400.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3401.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3402.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/07_23_Duesseldorf/DSCF3415.JPG').previewUrl().build(), '23.07. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130311.jpg').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130319.jpg').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130323.jpg').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130326.jpg').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130337.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130338.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130346.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130349.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130353.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130354.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130359.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130391.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2011/08_06_Duesseldorf/P1130392.JPG').previewUrl().build(), '06.08. Düsseldorf')
    .title('Rückblick')
    .titleImageUrl('https://content.rtc-koeln.de/pages/gallery/2011/preview/preview.01_01_Rueckblick.gif')
    .build()
