export default {
  albums: [
    {
      entries: [
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/594A7945-FDAF-4351-A214-BE53B0D24A1E.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1577.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1579.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1580.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1581.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1582.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1583.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1584.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1585.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1586.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1587.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1588.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1590.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1592.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1593.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1594.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1595.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1598.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1600.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1601.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1605.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1608.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1609.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1611.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1613.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1615.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1616.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1617.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1618.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1619.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1620.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1621.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1622.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1623.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1624.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1628.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1629.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1630.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1631.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1635.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1637.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1640.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1644.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1645.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1649.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1650.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1651.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1652.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1653.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1654.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1655.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1656.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1658.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1659.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1660.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1661.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5555.HEIC.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5557.heic.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5557_2.HEIC.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-1.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-2.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-3.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-4.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-5.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-6.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-7.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-8.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-9.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-10.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-11.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-12.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-13.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-14.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-15.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-16.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-17.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-18.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-19.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-20.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-21.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-22.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-23.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-24.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-25.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-26.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-27.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-28.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-29.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-30.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-31.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-32.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-33.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-34.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-35.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-36.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-37.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-38.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-39.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-40.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-41.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-42.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-43.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-44.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-45.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-46.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-47.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-48.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-49.jpg.avif') },
      ],
    },
  ],
  location: 'Mercure Hotel, Köln',
  time: {
    name: 'RTC-Feier zum 50. Jubiläum',
    start: new Date('2022-10-29'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/594A7945-FDAF-4351-A214-BE53B0D24A1E.jpg.avif'),
  youtubeVideoIds: ['qVYdx_pi9xE', 'gBVhgXredjI', 'pLWpFlQLP68'],
}
