import EntryBuilder from '~/models/builder/gallery/EntryBuilder'
import GalleryBuilder from '~/models/builder/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.RTC)
    .dateFrom(new Date('2013-05-26'))
    .dateTo(new Date('2013-12-23'))
    .location('Rösrath-Forsbach & Köln')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/07_23_Fotogalerie.gif').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_001.jpg').previewUrl().build(), '26.05. 41. Forsbach-Tour')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_002.jpg').previewUrl().build(), '26.05. 41. Forsbach-Tour')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_003.jpg').previewUrl().build(), '26.05. 41. Forsbach-Tour')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_004.jpg').previewUrl().build(), '26.05. 41. Forsbach-Tour')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_005.jpg').previewUrl().build(), '26.05. 41. Forsbach-Tour')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_006.jpg').previewUrl().build(), '26.05. 41. Forsbach-Tour')
    .image(
        new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc-forsbach-tour-flyer1-2013.jpg').previewUrl().build(),
        '26.05. 41. Forsbach-Tour'
    )
    .image(
        new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc-forsbach-tour-flyer2-2013.jpg').previewUrl().build(),
        '26.05. 41. Forsbach-Tour'
    )
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06682.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06683.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06692.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06696.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06698.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06703.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06704.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06707.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06709.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06711.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06712.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06713.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06714.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06717.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06718.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06721.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06724.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06725.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06726.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06729.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06736.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06737.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06738.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06744.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06745.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06747.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06752.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06754.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06757.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06761.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06762.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06763.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06764.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06768.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06776.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06777.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06778.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06780.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06781.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06785.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06786.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06787.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06788.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06789.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06791.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06792.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06793.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06794.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06802.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06804.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06805.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06807.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06808.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06809.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06810.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06811.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06812.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06813.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06814.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06815.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06818.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06819.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06820.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06821.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06823.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06827.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06828.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06829.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06830.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06831.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06832.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06833.JPG').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSCF2699.jpg').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSCF2702.jpg').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSCF2708.jpg').previewUrl().build(), '23.12. RTC Weihnachtsfeier')
    .image(
        new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/rtc_131207_002.jpg').previewUrl().build(),
        '23.12. RTC Weihnachtsfeier'
    )
    .image(
        new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/rtc-999-intro-jw-2013.jpg').previewUrl().build(),
        '23.12. RTC Weihnachtsfeier'
    )
    .title('Fotogalerie')
    .titleImageUrl('https://content.rtc-koeln.de/pages/gallery/2013/preview/preview.07_23_Fotogalerie.gif')
    .build()
