import EEvent from 'src/models/enums/EEvent'

export default {
  albums: [
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(10).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(11).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(12).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(13).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(14).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(15).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(16).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(17).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(18).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(19).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(1).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(20).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(21).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(22).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(23).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(24).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(25).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(26).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(27).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(28).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(29).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(2).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(30).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(31).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(32).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(33).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(34).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(35).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(36).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(37).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(38).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(39).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(3).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(40).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(41).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(42).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(43).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(44).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(45).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(4).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(5).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(6).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(7).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(8).JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(9).JPG.avif') },
  ],
  category: EEvent.Permanente,
  location: 'Köln - Lindlar',
  time: {
    name: 'Permanente "Das Bergische Karussell"',
    start: new Date('2014-03-29'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(35).JPG.avif'),
}
