import EEvent from 'src/models/enums/EEvent'

export default {
  albums: [
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0277.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0278.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0280.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0281.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0282.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0283.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0284.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0285.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0286.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0288.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0289.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0290.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0292.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0293.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0294.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0295.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0296.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0297.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0298.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0299.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0300.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0301.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0303.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0304.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0305.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0306.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0307.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0308.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0309.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0310.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0311.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0312.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5146.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5148.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5150.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5161.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5172.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5179.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5184.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5186.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5188.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5194.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5202.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00482.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00486.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00490.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00492.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00495.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-01.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-03.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-04.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-07.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-09.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-10.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-11.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-28.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-46.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-47.jpg.avif') },
  ],
  category: EEvent.Permanente,
  location: 'Großenlüder-Bimbach',
  time: {
    name: 'Permanente Großenlüder-"Bimbach"',
    start: new Date('2014-06-08'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5146.JPG.avif'),
}
