import EEvent from 'src/models/enums/EEvent'

export default {
  albums: [
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-01.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-02.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-03.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-04.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-05.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-06.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-07.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-08.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-09.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-10.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-11.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-12.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-13.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-14.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-15.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-16.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-17.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-18.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-19.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-20.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-21.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-22.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-23.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-24.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-25.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-26.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-27.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-28.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-29.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-30.jpg.avif') },
  ],
  category: EEvent.Vereinsfahrt,
  location: 'Erftstadt',
  time: {
    name: 'RTF Erftstadt',
    start: new Date('2014-06-21'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-20.jpg.avif'),
}
