import EEvent from 'src/models/enums/EEvent'

export default {
  albums: [
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-01.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-02.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-03.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-04.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-05.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-06.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-07.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-08.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-09.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-10.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-11.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-12.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-13.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-14.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-15.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-16.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-17.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-18.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-19.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-20.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-21.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-22.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-23.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-24.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-25.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-26.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-27.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-28.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-29.jpg.avif') },
  ],
  category: EEvent.Vereinsfahrt,
  location: 'Sundern',
  time: {
    name: 'RTF Sundern',
    start: new Date('2014-09-20'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2014/09_20_RTF_Sundern/rtc-sundern-12.jpg.avif'),
}
