export default [
  (await import('./03_29_Bergische_Karussell')).default,
  (await import('./04_03_Geburtstag_Erich_Fischer')).default,
  (await import('./04_08_Flandern_Belgien')).default,
  (await import('./04_12_Duesseldorf')).default,
  (await import('./05_04_Luelsdorf')).default,
  (await import('./05_14_Koeln_Rodenkirchen')).default,
  (await import('./05_25_RTF_42')).default,
  (await import('./05_31_Euskirchen')).default,
  (await import('./06_08_Großenlueder_Bimbach')).default,
  (await import('./06_19_Erkelenz')).default,
  (await import('./06_21_RTF_Erftstadt')).default,
  (await import('./06_29_RTF_Niederlande')).default,
  (await import('./07_13_Eslohe')).default,
  (await import('./09_01_RTF_Erden')).default,
  (await import('./09_20_RTF_Sundern')).default,
  (await import('./09_27_RTF_Quadrath_Ichendorf')).default,
  (await import('./10_12_Saisonabschluss')).default,
  (await import('./10_19_Ahrwanderung')).default,
  (await import('./10_25_Harry_Brot')).default,
  (await import('./11_28_Weihnachtsfeier')).default,
  (await import('./12_02_Siegerehrung_Mannschaftswertung_Bezirk_Koeln')).default,
  (await import('./Rueckblick')).default,
]
