import EventBuilder from '~/models/builder/events/calendar/EventBuilder'
import EEvent from '~/models/enums/EEvent'
import useCalendar from '~/utils/Calendar'

export default [
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-2-4 20:00', '2022-2-4 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Veranstaltung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-3-5')
        .setName('Start in das Jubiläumsjahr')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Abgesagt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-3-12')
        .setName('RTF Mistral Köln')
        .setUrl('rc-mistral.koeln')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(0)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-3-18 19:00', '2022-3-18 21:00')
        .setName('Jahreshauptversammlung')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-4-1 20:00', '2022-4-1 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder().setallDay(true).setCategory(EEvent.Permanente).setClubPoints(1).setContact('Klaus Dünkelmann').setDate('2022-4-9').setName('RTC Permanente').build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-5-1')
        .setName('RTF Staubwolke Refrath')
        .setUrl('rc-mistral.koeln')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-5-6 20:00', '2022-5-6 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.RTF)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-5-7')
        .setName('50. Forsbach – Tour - Marathon - Vortour')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-5-14')
        .setName('RTF Erftstadt')
        .setUrl('www.rsc-erftstadt.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.RTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-5-28')
        .setName('50. Forsbach – Tour - Marathon - Ausschildern')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.RTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-5-29')
        .setName('50. Forsbach – Tour - Marathon - Durchführung')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-6-3 20:00', '2022-6-3 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-6-12')
        .setName('RTF Lülsdorf')
        .setUrl('luera1959.de/radsportabteilung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-6-16', '2022-6-19')
        .setName('RTF Radsport Schrecksbach')
        .setUrl('www.radsport-schrecksbach.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-6-19')
        .setName('RTF Ford Köln')
        .setUrl('www.rsg-ford.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setName('RTF Rodenkirchen')
        .setDate('2022-6-26')
        .setUrl('rtc-rodenkirchen.de')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-7-1 20:00', '2022-7-1 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-7-30', '2022-7-24')
        .setName('BRT Schwerin')
        .setUrl('www.brt-2022.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-8-6')
        .setName('RTF Lohmar')
        .setUrl('sites.google.com/view/rtvlohmar/startseite')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-8-14')
        .setName('RTF Hennef')
        .setUrl('www.cito-hennef.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-8-27')
        .setName('RTF Rhein Energie')
        .setUrl('www.rheinenergie.com/de/privatkunden/wir_fuer_die_region/sportangebot/radsport/radsport.html')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-9-2 20:00', '2022-9-2 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-9-17')
        .setName('RTF Quadrath')
        .setUrl('www.rc-staubwolke-quadrath.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-10-3')
        .setName('RTF Radsport Schmitter Hürth')
        .setUrl('www.rc-schmitter.de')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-10-7 20:00', '2022-10-7 22:00')
        .setName('Mitgliederversammlung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.CTF)
        .setClubPoints(4)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-10-16')
        .setName('7. Wahnbach – Tour - Gravel - Vortour')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.CTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-10-21')
        .setName('7. Wahnbach – Tour - Gravel - Ausschildern')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.CTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-10-22')
        .setName('7. Wahnbach – Tour - Gravel - Durchführung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.CTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2022-10-23')
        .setName('7. Wahnbach – Tour - Gravel - Abschildern')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(0)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-10-29 18:00', '2022-10-29 22:00')
        .setName('Weihnachtsfeier')
        .build(),
    new EventBuilder()
        .setallDay(false)
        .setCategory(EEvent.Mitgliederversammlung)
        .setClubPoints(1)
        .setContact('Wolfgang Dünkelmann')
        .setDate('2022-11-4 19:00', '2022-11-4 21:00')
        .setName('Mitgliederversammlung')
        .build(),
].concat(useCalendar().getHolidays(new Date().getFullYear()))
