import EventBuilder from '~/models/builder/events/calendar/EventBuilder'
import EEvent from '~/models/enums/EEvent'
import useCalendar from '~/utils/Calendar'

export default [
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-3-11')
        .setName('RTF Mistral Köln')
        .setUrl('rc-mistral.koeln')
        .build(),
    new EventBuilder().setallDay(true).setCategory(EEvent.Permanente).setClubPoints(1).setContact('Klaus Dünkelmann').setDate('2023-4-15').setName('RTC Permanente').build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-5-1')
        .setName('RTF Staubwolke Refrath')
        .setUrl('rc-mistral.koeln')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-5-13')
        .setName('RTF Erftstadt')
        .setUrl('www.rsc-erftstadt.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.RTF)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-5-20')
        .setName('51. Forsbach – Tour - Marathon - Vortour')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.RTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-5-27')
        .setName('51. Forsbach – Tour - Marathon - Ausschildern')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.RTF)
        .setClubPoints(5)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-5-28')
        .setName('51. Forsbach – Tour - Marathon')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-6-3')
        .setName('RTF Euskirchen')
        .setUrl('rsv-euskirchen.de/informationen-rtf-neu')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-6-11')
        .setName('RTF Lülsdorf')
        .setUrl('luera1959.de/radsportabteilung')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-6-8', '2023-6-11')
        .setName('RTF Radsport Schrecksbach')
        .setUrl('www.radsport-schrecksbach.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-6-18')
        .setName('RTF Ford Köln')
        .setUrl('www.rsg-ford.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setName('RTF Rodenkirchen')
        .setDate('2023-6-25')
        .setUrl('rtc-rodenkirchen.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-7-1')
        .setName('RTF Uckerath')
        .setUrl('radsport.sc-uckerath.de/mauer-von-uckerath/')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-8-5')
        .setName('RTF Lohmar')
        .setUrl('sites.google.com/view/rtvlohmar/startseite')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-8-13')
        .setName('RTF Hennef')
        .setUrl('www.cito-hennef.de')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-8-26')
        .setName('RTF Rhein Energie')
        .setUrl('www.rheinenergie.com/de/privatkunden/wir_fuer_die_region/sportangebot/radsport/radsport.html')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-9-2')
        .setName('RTF Malefinkbach')
        .setUrl('www.svmalefinkbach.de/rtf/')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-9-16')
        .setName('RTF Welldorf')
        .setUrl('www.rscwelldorf.de/html/rtf.html')
        .build(),
    new EventBuilder()
        .setallDay(true)
        .setCategory(EEvent.Vereinsfahrt)
        .setClubPoints(2)
        .setContact('Klaus Dünkelmann')
        .setDate('2023-9-30')
        .setName('RTF Büttgen')
        .setUrl('rtf-buettgen.de/herbst-rtf')
        .build(),
]
