export default {
  albums: [
    {
      entries: [
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9708.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9723.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9732.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9745.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9748.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9752.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9754.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9755.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9757.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9758.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9760.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9762.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9763.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9765.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9767.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9769.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9773.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9775.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9776.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9777.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9779.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9780.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9781.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9782.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9792.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9800.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9807.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9813.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9816.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9822.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9827.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9829.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9830.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9832.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9835.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9837.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9839.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9842.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9848.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9849.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9852.JPG.avif') },
      ],
    },
  ],
  location: 'Köln',
  time: {
    name: 'Schrauber-Workshop beim RTC Köln e.V.',
    start: new Date('2024-03-16'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2024/03_16_Schrauberworkshop/IMG_9773.JPG.avif'),
}
