/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//events/calendar'
      | '//events/tours/permanents'
      | '//events/tours/rtfs/(index)'
      | '//events/tours/rtfs/family'
      | '//events/tours/rtfs/suggestions'
      | '//events/tours/stagerace'
      | '//events/training'
      | '//imprint'
      | '//membership-registration'
      | '//privacy-and-security'
      | '//rtc-cologne/about-us'
      | '//rtc-cologne/contacts'
      | '//rtc-cologne/galleries/(index)'
      | '//rtc-cologne/galleries/[id]_[[album]]'
      | '//rtc-cologne/guestbook'
      | '//rtc-cologne/our-story'
      | '//rtc-cologne/press-reports'
      | '//sponsors'
      | 'home'
    >,
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/calendar': RouteRecordInfo<
      '//events/calendar',
      '/events/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/tours/permanents': RouteRecordInfo<
      '//events/tours/permanents',
      '/events/tours/permanents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/tours/rtfs/(index)': RouteRecordInfo<
      '//events/tours/rtfs/(index)',
      '/events/tours/rtfs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/tours/rtfs/family': RouteRecordInfo<
      '//events/tours/rtfs/family',
      '/events/tours/rtfs/family',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/tours/rtfs/suggestions': RouteRecordInfo<
      '//events/tours/rtfs/suggestions',
      '/events/tours/rtfs/suggestions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/tours/stagerace': RouteRecordInfo<
      '//events/tours/stagerace',
      '/events/tours/stagerace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//events/training': RouteRecordInfo<
      '//events/training',
      '/events/training',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//imprint': RouteRecordInfo<
      '//imprint',
      '/imprint',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//membership-registration': RouteRecordInfo<
      '//membership-registration',
      '/membership-registration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//privacy-and-security': RouteRecordInfo<
      '//privacy-and-security',
      '/privacy-and-security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//rtc-cologne/about-us': RouteRecordInfo<
      '//rtc-cologne/about-us',
      '/rtc-cologne/about-us',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//rtc-cologne/contacts': RouteRecordInfo<
      '//rtc-cologne/contacts',
      '/rtc-cologne/contacts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//rtc-cologne/galleries/(index)': RouteRecordInfo<
      '//rtc-cologne/galleries/(index)',
      '/rtc-cologne/galleries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//rtc-cologne/galleries/[id]_[[album]]': RouteRecordInfo<
      '//rtc-cologne/galleries/[id]_[[album]]',
      '/rtc-cologne/galleries/:id()_:album?',
      { id: ParamValue<true>, album?: ParamValueZeroOrOne<true> },
      { id: ParamValue<false>, album?: ParamValueZeroOrOne<false> },
      | never
    >,
    '//rtc-cologne/guestbook': RouteRecordInfo<
      '//rtc-cologne/guestbook',
      '/rtc-cologne/guestbook',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//rtc-cologne/our-story': RouteRecordInfo<
      '//rtc-cologne/our-story',
      '/rtc-cologne/our-story',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//rtc-cologne/press-reports': RouteRecordInfo<
      '//rtc-cologne/press-reports',
      '/rtc-cologne/press-reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sponsors': RouteRecordInfo<
      '//sponsors',
      '/sponsors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/error500': RouteRecordInfo<
      '/error500',
      '/error500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//events/calendar'
        | '//events/tours/permanents'
        | '//events/tours/rtfs/(index)'
        | '//events/tours/rtfs/family'
        | '//events/tours/rtfs/suggestions'
        | '//events/tours/stagerace'
        | '//events/training'
        | '//imprint'
        | '//membership-registration'
        | '//privacy-and-security'
        | '//rtc-cologne/about-us'
        | '//rtc-cologne/contacts'
        | '//rtc-cologne/galleries/(index)'
        | '//rtc-cologne/galleries/[id]_[[album]]'
        | '//rtc-cologne/guestbook'
        | '//rtc-cologne/our-story'
        | '//rtc-cologne/press-reports'
        | '//sponsors'
        | 'home'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | 'home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/calendar.vue': {
      routes:
        | '//events/calendar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/tours/permanents.vue': {
      routes:
        | '//events/tours/permanents'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/tours/rtfs/(index).vue': {
      routes:
        | '//events/tours/rtfs/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/tours/rtfs/family.vue': {
      routes:
        | '//events/tours/rtfs/family'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/tours/rtfs/suggestions.vue': {
      routes:
        | '//events/tours/rtfs/suggestions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/tours/stagerace.vue': {
      routes:
        | '//events/tours/stagerace'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/events/training.vue': {
      routes:
        | '//events/training'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/imprint.vue': {
      routes:
        | '//imprint'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/membership-registration.vue': {
      routes:
        | '//membership-registration'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/privacy-and-security.vue': {
      routes:
        | '//privacy-and-security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/rtc-cologne/about-us.vue': {
      routes:
        | '//rtc-cologne/about-us'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/rtc-cologne/contacts.vue': {
      routes:
        | '//rtc-cologne/contacts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/rtc-cologne/galleries/(index).vue': {
      routes:
        | '//rtc-cologne/galleries/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/rtc-cologne/galleries/[id]_[[album]].vue': {
      routes:
        | '//rtc-cologne/galleries/[id]_[[album]]'
      views:
        | never
      pathParamNames:
        | 'album'
        | 'id'
    }
    'src/pages/index/rtc-cologne/guestbook.vue': {
      routes:
        | '//rtc-cologne/guestbook'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/rtc-cologne/our-story.vue': {
      routes:
        | '//rtc-cologne/our-story'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/rtc-cologne/press-reports.vue': {
      routes:
        | '//rtc-cologne/press-reports'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/sponsors.vue': {
      routes:
        | '//sponsors'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/error500.vue': {
      routes:
        | '/error500'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
