import { Pinia } from 'pinia'
import { useRepo } from 'pinia-orm'
import GalleryAlbumEntry from 'src/models/entities/rtc-cologne/gallery/GalleryAlbumEntry'

export default (store: Pinia) =>
  useRepo(GalleryAlbumEntry, store).save([
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image0_61fe6032-2f8a-4344-a6cc-b91d395eca08.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image1_d322962f-3531-4248-8f64-f1fe3f3850b8.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image2_4f36deec-6f19-4992-9ab3-3ea2a84b1572.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image3_e788fefb-5518-4e6c-a594-d93c96dfdfd2.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image0.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image1.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image2.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image3.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_2571.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/b74ba152-d427-40ac-8ef4-4539bcb153e3.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/b0a3d468-828d-474d-9380-e568a38fad89.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_0037.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_2225.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4226.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4235.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4241.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4252.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4256.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4483.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4495.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4497.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4502.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4507.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4508.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_4515.jpg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/signal-2023-02-05-092407_002.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/signal-2023-02-05-092407_003.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_0936.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_0923.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/IMG_0909.JPG.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image4.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image7.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image8.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image9.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image10.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image11.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image12.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image13.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/image14.jpeg.avif') },
    { imageUrl: new URL('https://content.rtc-koeln.de/pages/home/slideshow/signal-2023-05-01-193158.jpeg.avif') },
  ])
