import EntryBuilder from '~/models/builder/about-us/gallery/EntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'

export default new GalleryBuilder()
    .dateFrom(new Date('2012-04-08'))
    .dateTo(new Date('2012-12-11'))
    .location('Köln & Düsseldorf')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/08_15_Rueckblick.gif').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/16-IMG_5514-1.jpg').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0851.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0854.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0856.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0858.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0859.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0860.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0862.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0863.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0865.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0868.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0870.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0872.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0874.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0876.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0878.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0880.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0888.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0889.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0890.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0892.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0894.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0896.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0897.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0900.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0901.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0902.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0909.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0910.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0911.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0912.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0915.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0917.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0918.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0920.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0921.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0922.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0923.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0925.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0926.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0927.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0935.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0936.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0939.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0941.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0942.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0943.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0950.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0951.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0955.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0990.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/CIMG0992.JPG').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/kurt 002.jpg').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_08_Jubilaeumsfahrt/kurt 005.jpg').previewUrl().build(), '08.04. Jubiläumsfahrt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/04_14_GWR_Duesseldorf/CIMG0509.JPG').previewUrl().build(), '14.04. GWR Düsseldorf')
    .image(
        new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/12_11_Weihnachtsfeier/Weihnachsfeier RTC 2012 (10).JPG').previewUrl().build(),
        '11.12. RTC Weihnachtsfeier'
    )
    .image(
        new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2012/12_11_Weihnachtsfeier/Weihnachsfeier RTC 2012 (1).JPG').previewUrl().build(),
        '11.12. RTC Weihnachtsfeier'
    )
    .title('Rückblick')
    .titleImageUrl('https://content.rtc-koeln.de/pages/gallery/2012/preview/preview.08_15_Rueckblick.gif')
    .build()
