import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'

export default new GalleryBuilder()
    .dateFrom('2013-05-26')
    .dateTo('2013-12-23')
    .location('Rösrath-Forsbach & Köln')
    .images({
        '': [new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/07_23_Rueckblick.gif').build()],
        '26.05. 41. Forsbach-Tour': [
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_001.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_002.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_003.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_004.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_005.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc_131006_006.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc-forsbach-tour-flyer1-2013.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/05_26_RTF_41/rtc-forsbach-tour-flyer2-2013.jpg').build(),
        ],
        '23.12. RTC Weihnachtsfeier': [
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06682.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06683.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06692.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06696.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06698.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06703.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06704.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06707.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06709.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06711.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06712.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06713.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06714.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06717.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06718.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06721.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06724.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06725.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06726.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06729.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06736.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06737.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06738.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06744.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06745.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06747.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06752.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06754.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06757.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06761.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06762.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06763.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06764.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06768.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06776.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06777.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06778.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06780.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06781.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06785.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06786.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06787.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06788.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06789.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06791.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06792.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06793.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06794.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06802.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06804.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06805.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06807.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06808.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06809.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06810.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06811.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06812.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06813.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06814.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06815.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06818.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06819.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06820.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06821.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06823.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06827.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06828.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06829.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06830.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06831.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06832.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSC06833.JPG').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSCF2699.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSCF2702.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/DSCF2708.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/rtc_131207_002.jpg').build(),
            new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2013/12_23_RTC_Weihnachtsfeier/rtc-999-intro-jw-2013.jpg').build(),
        ],
    })
    .title('Rückblick')
    .titleImageUrl('content.rtc-koeln.de/pages/gallery/2013/preview/preview.07_23_Rueckblick.gif')
    .build()
