export default {
  albums: [
    {
      entries: [
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/022d591e-89e2-4202-9226-8c9ec683c2d8.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/6c2154dc-abb3-44a4-8024-66a1933d2f20.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/814a34d4-3330-4725-bead-e473359da212.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/a366cc1b-bfdd-4d74-98cc-fa641c618a10.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/b0a3d468-828d-474d-9380-e568a38fad89.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/b1f2d2d5-c9c3-4241-bc4e-c81ea2f0bc61.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/b8aab3ff-ce1d-4a82-87a7-3dcc235e82da.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/bdbd2d19-91e0-45dd-9f12-73a186262f5b.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/cfb9b45e-9b28-45a8-a9e7-e0b272614dbc.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0026.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0028.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0030.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0033.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0035.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0037.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0041.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_0044.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2088.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2092.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2094.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2208.png.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2222.png.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2223.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2225.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2277.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2279.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2280.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2281.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2282.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2402.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2523.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2527.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2534.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2536.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2540.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2542.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2543.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2544.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2610.png.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2716.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2722.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2723.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2725.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2775.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2776.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2779.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2809.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2854.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2868.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2880.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2882.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_2927.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3001.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3003.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3005.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3046.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3092.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3113.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3120.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3122.png.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3130.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3188.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4143.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4144.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4152.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4158.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4161.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4215.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4226.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4227.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4231.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4233.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4235.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4236.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4239.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4241.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4242.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4246.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4247.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4250.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4252.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4256.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4483.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4491.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4492.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4495.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4497.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4501.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4502.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4507.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4508.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4510.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4515.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4559.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4561.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4644.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4647.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4649.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4650.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4651.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4652.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4653.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4654.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4655.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4656.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4657.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4658.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4660.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4661.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4665.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4667.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4671.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4681.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4682.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4684.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4686.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4687.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4688.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4689.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4692.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4696.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4844.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4854.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4870.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4877.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_4878.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5074.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5089.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5218.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5219.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5220.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5224.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5226.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5400.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5404.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5405.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5429.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5527.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_5872.jpeg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/Bruni_Trierweiler_Nachruf.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/alien-g455fb5f12_1920.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/christmas-tree-gc3765cc93_1920.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/Wolfgang_Becker_Nachruf.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/RTC Logo 720px.png.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/RTC Logo 720px_withHat.png.avif') },
      ],
    },
  ],
  location: 'Köln',
  time: {
    name: 'Rückblick',
    start: new Date('2021-12-31'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2021/Rueckblick/IMG_3003.jpeg.avif'),
  youtubeVideoIds: ['aM72rMzksv8', 'gjC3McWSW0o', 'jNk79zf_C6I', 'nH6HEDPe90c', 'pBKRgqct0N0', 'VvXDcCJ2AN4', 'wgNWl3jO0k0', 'WC2WSRXAaOs', 'yNdBHkQXMaQ'],
}
