import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'
import _0330Streckenbesichtigung from '~/store/about-us/gallery/2014/05_25_RTF_42/03_30_Streckenbesichtigung'
import Tour from '~/store/about-us/gallery/2014/05_25_RTF_42/Tour'

export default new GalleryBuilder()
    .category(EEvent.RTF)
    .dateFrom(new Date('2014-05-25'))
    .location('Köln')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/rtc-forsbach-tour-flyer1-2014.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/rtc-forsbach-tour-flyer2-2014.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/05_17_Vortour/DSCF4964.JPG').previewUrl().build(), '17.05. Vortour')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/05_17_Vortour/DSCF4965.JPG').previewUrl().build(), '17.05. Vortour')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/05_17_Vortour/DSCF4967.JPG').previewUrl().build(), '17.05. Vortour')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/05_17_Vortour/Huelstert2.JPG').previewUrl().build(), '17.05. Vortour')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/05_17_Vortour/Huelstert.JPG').previewUrl().build(), '17.05. Vortour')
    .image(
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Kontrolle_Huelstert/IMG_0293[1].JPG').previewUrl().build(),
        'Kontrolle Huelstert'
    )
    .image(
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Kontrolle_Huelstert/IMG_0294[1].JPG').previewUrl().build(),
        'Kontrolle Huelstert'
    )
    .image(
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Kontrolle_Huelstert/IMG_0296[1].JPG').previewUrl().build(),
        'Kontrolle Huelstert'
    )
    .image(
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Kontrolle_Huelstert/IMG_0297[1].JPG').previewUrl().build(),
        'Kontrolle Huelstert'
    )
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(10).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(11).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(12).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(13).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(14).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(15).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(16).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(17).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(18).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(19).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(1).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(20).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(21).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(22).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(23).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(24).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(25).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(26).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(27).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(28).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(29).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(2).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(30).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(31).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(32).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(33).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(34).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(35).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(36).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(37).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(38).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(39).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(3).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(40).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(41).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(42).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(43).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(44).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(45).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(46).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(47).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(48).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(49).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(4).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(50).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(51).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(52).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(53).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(54).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(55).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(56).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(57).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(58).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(59).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(5).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(60).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(61).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(62).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(63).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(64).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(65).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(66).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(67).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(6).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(7).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(8).JPG').previewUrl().build(), 'Marathon')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/Marathon/Forsbach-Marathon(9).JPG').previewUrl().build(), 'Marathon')
    .images(_0330Streckenbesichtigung)
    .images(Tour)
    .title('42. Forsbach-Tour')
    .titleImageUrl('content.rtc-koeln.de/pages/gallery/2014/05_25_RTF_42/preview/preview.rtc-forsbach-tour-flyer1-2014.jpg')
    .build()
