import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.Permanente)
    .dateFrom('2014-06-08')
    .location('Großenlüder-Bimbach')
    .images([
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0277.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0278.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0280.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0281.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0282.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0283.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0284.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0285.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0286.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0288.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0289.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0290.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0292.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0293.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0294.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0295.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0296.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0297.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0298.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0299.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0300.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0301.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0303.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0304.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0305.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0306.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0307.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0308.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0309.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0310.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0311.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0312.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5146.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5148.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5150.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5161.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5172.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5179.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5184.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5186.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5188.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5194.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5202.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00482.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00486.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00490.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00492.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00495.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-01.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-03.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-04.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-07.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-09.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-10.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-11.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-28.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-46.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-47.jpg').build(),
    ])
    .title('Permanente Großenlüder-"Bimbach"')
    .titleImageUrl('content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/preview/preview.DSCF5146.JPG')
    .build()
