import EntryBuilder from '~/models/builder/about-us/gallery/EntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.Vereinsfahrt)
    .dateFrom(new Date('2014-06-21'))
    .location('Erftstadt')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-01.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-02.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-03.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-04.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-05.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-06.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-07.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-08.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-09.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-10.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-11.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-12.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-13.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-14.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-15.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-16.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-17.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-18.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-19.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-20.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-21.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-22.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-23.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-24.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-25.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-26.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-27.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-28.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-29.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/rtc-erftstadt-30.jpg').previewUrl().build())
    .title('RTF Erftstadt')
    .titleImageUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_21_RTF_Erftstadt/preview/preview.rtc-erftstadt-20.jpg')
    .build()
