import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.Veranstaltung)
    .dateFrom(new Date('2014-10-12'))
    .location('Köln')
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5699.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5709.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5710.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5715.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5717.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5718.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5722.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5724.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/DSCF5729.JPG').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-02.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-03.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-04.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-05.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-06.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-13.jpg').previewUrl().build())
    .image(new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/rtc-20141012-abschlt-14.jpg').previewUrl().build())
    .title('Saisonabschluss')
    .titleImageUrl('content.rtc-koeln.de/pages/gallery/2014/10_12_Saisonabschluss/preview/preview.DSCF5699.JPG')
    .build()
