import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'

export default new GalleryBuilder()
    .date('2014-11-28')
    .location('Köln')
    .images([
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1701.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1702.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1703.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1704.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1705.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1706.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1707.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1708.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1709.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1711.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1712.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1713.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1714.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1716.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1717.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1718.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1720.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1721.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1722.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1723.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1725.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1726.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1727.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1728.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1729.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1730.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1732.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1734.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1740.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1741.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1742.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1743.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1744.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1745.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1747.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1749.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1751.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1753.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1754.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1755.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1756.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/CIMG1757.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01667.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01668.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01669.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01671.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01675.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01680.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01681.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01682.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01683.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01686.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01687.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01690.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01702.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01709.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01713.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01716.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01719.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01720.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01722.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01723.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01732.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01733.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01736.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01738.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01739.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01742.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01743.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01744.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01746.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01747.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01750.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/DSC01751.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/rtc-20141128-wf-02.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/rtc-20141128-wf-07.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/rtc-20141128-wf-21.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-0.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-1.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-2.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-3.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-4.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-5.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-6.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-7.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-8.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-9.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-10.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-11.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-12.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-13.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-14.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-15.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-16.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-17.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-18.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-19.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-20.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-21.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-22.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-23.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-24.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-25.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-26.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-27.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-28.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/Sieger2015b-29.jpg').build(),
    ])
    .title('Weihnachtsfeier')
    .titleImageUrl('content.rtc-koeln.de/pages/gallery/2014/11_28_Weihnachtsfeier/preview/preview.DSC01751.JPG')
    .build()
