export default {
  albums: [
    {
      entries: [
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/6e907c58-e89d-417f-b420-7863eb9ba6d7.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/71420221654__7EC61BA2-D991-4764-B484-F39DF0D82387.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/77b8ea68-ebef-440c-ba42-2d236f626fb8.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/8c9ed2a2-dd61-4f4a-a353-045d4eddb11b.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5008.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5013.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5018.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5019.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5022.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5026.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5028.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5029.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5031.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5033.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5034.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5036.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5038.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5039.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5041.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5046.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5048.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5049.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5055.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5058.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5059.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5061.JPG.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_7255.jpg.avif') },
        { imageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_7256.jpg.avif') },
      ],
    },
  ],
  location: 'Köln-Lövenich',
  time: {
    name: 'Großes RTC-Aufgebot in Lövenich 🚴‍♀️',
    start: new Date('2023-08-20'),
  },
  titleImageUrl: new URL('https://content.rtc-koeln.de/pages/gallery/2023/08_20_Grosses_RTC-Aufgebot_in_Loevenich/IMG_5061.JPG.avif'),
}
