import EntryBuilder from '~/models/builder/gallery/EntryBuilder'
import GalleryBuilder from '~/models/builder/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.Permanente)
    .dateFrom(new Date('2014-03-29'))
    .location('Köln - Lindlar')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(10).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(11).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(12).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(13).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(14).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(15).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(16).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(17).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(18).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(19).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(1).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(20).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(21).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(22).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(23).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(24).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(25).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(26).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(27).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(28).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(29).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(2).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(30).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(31).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(32).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(33).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(34).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(35).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(36).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(37).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(38).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(39).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(3).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(40).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(41).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(42).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(43).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(44).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(45).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(4).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(5).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(6).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(7).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(8).JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/Bergische Karussell(9).JPG').previewUrl().build())
    .title('Permanente "Bergisches Karussell"')
    .titleImageUrl('https://content.rtc-koeln.de/pages/gallery/2014/03_29_Bergisches_Karussell/preview/preview.Bergische Karussell(35).JPG')
    .build()
