import EntryBuilder from '~/models/builder/gallery/EntryBuilder'
import GalleryBuilder from '~/models/builder/GalleryBuilder'
import EEvent from '~/models/enums/EEvent'

export default new GalleryBuilder()
    .category(EEvent.Permanente)
    .dateFrom(new Date('2014-06-08'))
    .location('Großenlüder-Bimbach')
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0277.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0278.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0280.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0281.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0282.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0283.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0284.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0285.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0286.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0288.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0289.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0290.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0292.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0293.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0294.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0295.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0296.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0297.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0298.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0299.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0300.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0301.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0303.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0304.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0305.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0306.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0307.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0308.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0309.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0310.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0311.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/CIMG0312.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5146.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5148.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5150.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5161.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5172.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5179.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5184.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5186.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5188.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5194.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/DSCF5202.JPG').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00482.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00486.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00490.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00492.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/IMG-20140608-00495.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-01.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-03.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-04.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-07.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-09.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-10.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-11.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-28.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-46.jpg').previewUrl().build())
    .image(new EntryBuilder().srcUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/rtc-bimb-47.jpg').previewUrl().build())
    .title('Permanente Großenlüder-"Bimbach"')
    .titleImageUrl('https://content.rtc-koeln.de/pages/gallery/2014/06_08_Grossenlueder_Bimbach/preview/preview.DSCF5146.JPG')
    .build()
