import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'

export default new GalleryBuilder()
    .date('2022-10-29')
    .id('8db60fe5-0c25-4d78-b4af-d5bae1cc4bfb')
    .location('Mercure Hotel, Köln')
    .images([
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/594A7945-FDAF-4351-A214-BE53B0D24A1E.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1577.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1579.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1580.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1581.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1582.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1583.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1584.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1585.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1586.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1587.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1588.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1590.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1592.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1593.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1594.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1595.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1598.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1600.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1601.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1605.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1608.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1609.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1611.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1613.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1615.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1616.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1617.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1618.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1619.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1620.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1621.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1622.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1623.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1624.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1628.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1629.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1630.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1631.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1635.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1637.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1640.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1644.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1645.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1649.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1650.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1651.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1652.jpg').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1653.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1654.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1655.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1656.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1658.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1659.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1660.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1661.JPG').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5555.HEIC').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5557.heic').build(),
        new GalleryEntryBuilder().imageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5557_2.HEIC').build(),
    ])
    .title('RTC-Feier zum 50. Jubiläum')
    .titleImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/preview/preview.594A7945-FDAF-4351-A214-BE53B0D24A1E.jpg')
    .youtubeVideoIds('qVYdx_pi9xE', 'gBVhgXredjI', 'pLWpFlQLP68')
    .build()
