import GalleryEntryBuilder from '~/models/builder/about-us/gallery/GalleryEntryBuilder'
import GalleryBuilder from '~/models/builder/about-us/GalleryBuilder'

export default new GalleryBuilder()
    .setDate('2022-10-29')
    .setId('8db60fe5-0c25-4d78-b4af-d5bae1cc4bfb')
    .setLocation('Mercure Hotel, Köln')
    .setImages([
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/594A7945-FDAF-4351-A214-BE53B0D24A1E.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1577.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1579.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1580.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1581.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1582.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1583.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1584.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1585.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1586.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1587.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1588.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1590.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1592.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1593.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1594.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1595.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1598.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1600.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1601.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1605.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1608.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1609.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1611.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1613.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1615.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1616.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1617.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1618.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1619.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1620.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1621.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1622.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1623.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1624.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1628.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1629.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1630.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1631.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1635.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1637.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1640.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1644.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1645.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1649.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1650.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1651.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1652.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1653.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1654.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1655.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1656.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1658.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1659.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1660.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_1661.JPG').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5555.HEIC').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5557.heic').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/IMG_5557_2.HEIC').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-1.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-2.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-3.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-4.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-5.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-6.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-7.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-8.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-9.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-10.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-11.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-12.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-13.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-14.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-15.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-16.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-17.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-18.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-19.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-20.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-21.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-22.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-23.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-24.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-25.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-26.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-27.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-28.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-29.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-30.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-31.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-32.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-33.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-34.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-35.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-36.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-37.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-38.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-39.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-40.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-41.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-42.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-43.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-44.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-45.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-46.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-47.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-48.jpg').build(),
        new GalleryEntryBuilder().setImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/RTC_Gruppe_Mosel_70erJahre-49.jpg').build(),
    ])
    .setTitle('RTC-Feier zum 50. Jubiläum')
    .setTitleImageUrl('content.rtc-koeln.de/pages/gallery/2022/10_29_Weihnachtsfeier/preview/preview.594A7945-FDAF-4351-A214-BE53B0D24A1E.jpg')
    .setYoutubeVideoIds('qVYdx_pi9xE', 'gBVhgXredjI', 'pLWpFlQLP68')
    .build()
