name: Generate Release
on:
    push:
        tags:
            - 'v*'
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  generate_release_notes: true
