name: Generate Release
on:
    push:
        tags:
            - 'v*'
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
            - name: Release
              uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
              with:
                  generate_release_notes: true
